hangman_words = [
    "apple", "banana", "orange", "grape", "peach", "melon", "lemon", "cherry", "berry", "kiwi",
    "table", "chair", "window", "curtain", "sofa", "mirror", "drawer", "pillow", "blanket", "carpet",
    "laptop", "monitor", "keyboard", "mouse", "screen", "charger", "battery", "speaker", "camera", "printer",
    "python", "coding", "binary", "debug", "syntax", "script", "module", "object", "method", "string",
    "planet", "galaxy", "rocket", "saturn", "venus", "earth", "neptune", "jupiter", "asteroid", "comet",
    "school", "student", "teacher", "pencil", "eraser", "marker", "notebook", "subject", "lesson", "lecture",
    "animal", "zebra", "giraffe", "tiger", "lion", "monkey", "rabbit", "parrot", "donkey", "squirrel",
    "beauty", "magic", "mystery", "dream", "shadow", "danger", "hunter", "forest", "legend", "secret",
    "doctor", "nurse", "clinic", "tablet", "syringe", "vaccine", "bandage", "injury", "fever", "patient",
    "engine", "brakes", "bumper", "mirror", "clutch", "radiator", "tire", "steering", "window", "gearbox",
    "desert", "tunnel", "jungle", "beach", "island", "valley", "canyon", "mountain", "volcano", "waterfall",
    "castle", "knight", "sword", "shield", "battle", "crown", "kingdom", "palace", "dragon", "armor",
    "guitar", "violin", "drums", "flute", "trumpet", "piano", "harp", "trombone", "banjo", "clarinet",
    "butter", "cheese", "yogurt", "honey", "ketchup", "mustard", "mayonnaise", "chocolate", "pepper", "cereal",
    "bottle", "bucket", "broom", "basket", "ladder", "rope", "scissors", "shovel", "hammer", "wrench",
    "summer", "winter", "autumn", "spring", "season", "sunset", "rainbow", "breeze", "storm", "weather",
    "pirate", "treasure", "ocean", "sailor", "island", "map", "ship", "anchor", "compass", "crew",
    "smile", "laugh", "happy", "peace", "brave", "lucky", "honest", "kind", "silly", "gentle",
    "cloud", "storm", "lightning", "thunder", "breeze", "hail", "snow", "fog", "climate", "forecast",
    "actor", "movie", "scene", "drama", "script", "director", "camera", "trailer", "dialogue", "audition",
    "cookie", "donut", "candy", "pudding", "sundae", "waffle", "pancake", "caramel", "brownie", "muffin",
    "button", "zipper", "collar", "sleeve", "jacket", "sweater", "blazer", "sock", "glove", "scarf",
    "engineer", "scientist", "pilot", "farmer", "lawyer", "artist", "painter", "plumber", "driver", "chef",
    "rocket", "launch", "gravity", "astronaut", "satellite", "orbit", "mission", "module", "probe", "spacesuit"
]
